# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 남궁권
title: 백엔드 엔지니어
email: rndrnjs2003@naver.com
website: https://kkoon9.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: kkoon9

# Additional icon links
# additional_links:
#   - title: Link name
#     icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#     url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About Me (Use this to override about section title)
about_profile_image: images/kkoon9.jpeg
about_content: |
  안녕하세요. 제가 읽었던 책과 들었던 인강을 소개하는 페이지입니다.

  저는 4년차 백엔드 개발자입니다.

    개발 서적을 주로 읽었기 때문에 백엔드 개발에 관심이 있으신 분들께 도움이 됐으면 좋겠습니다.

content:
  - title: Books
    layout: list
    content:
      - layout: right
        title: 실패는 나침반이다
        caption: July 2024 - July 2024
        link: https://product.kyobobook.co.kr/detail/S000212569197
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: |
          이 책은 개발자의 길을 고민하거나 개발자로 일하면서 중장기적인 계획을 하고 계시는 분께 추천드립니다.

          가장 인상깊었던 부분은 경력단절(휴식기)에 대한 내용과 실패에 대한 내용입니다.

          이 책에서는 휴식기야말로 인생을 되돌아볼 수 있는 좋은 기회라고 설명합니다.

          간혹 어떠한 기술을 쓰다가 큰 장애를 겪었을 때 장애 이유를 그 기술에서 찾아버리곤 그 기술을 다시는 쓰려고 하지 않는 개발자가 있다고 이야기합니다.

          그 실패를 분석하고 진짜 기술적 결함이 있다면 어떻게 극복할지 혹은 왜 사용하지 않게 되었는지 알아보는 게 더 나은 개발자가 될 수 있는 길이라고 설명하고 있었습니다.
      - layout: right
        title: 코틀린 동시성 프로그래밍
        caption: June 2024 - June 2024
        link: https://m.yes24.com/Goods/Detail/90338766
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: |
          이 책은 코틀린에서 사용하는 동시성 프로그래밍에 대한 이론이 잘 정리된 책입니다.

          최근 회사에서 코루틴을 사용하고 있어서 이에 대한 학습을 하고자 책을 읽기 시작했습니다.

          실습해 볼 수 있는 코드가 많아서 학습하기에 좋았습니다.

          다만, 이 책은 안드로이드 중심으로 설명하고 있는 책이라 백엔드 개발자 입장으로서는 조금 아쉬웠습니다.
      - layout: right
        title: 카프카, 데이터 플랫폼의 최강자
        caption: April 2023 - April 2023
        link: http://www.yes24.com/Product/Goods/59789254
        quote: >
          <mark>별점</mark> : ★★★★★
        description: |
          이 책은 카프카에 대한 이론이 잘 정리된 책입니다.

          면접에서 kafka 질문에 왕창 깨진 뒤, 속성으로 공부 및 정리했는데 제법 대답이 됐던 것 같습니다.

          이론용으로 강추!! 실습용은 제가 안해봐서 모르겠습니다..
      - layout: right
        title: 소프트웨어 장인
        caption: January 2023 - January 2023
        link: https://kkoon9.tistory.com/493
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: |
          이 책은 이름 그대로 소프트웨어 장인이 되기 위한 목표를 재정비해주는 책입니다.

          허나, 이 장인정신이 모든 소프트웨어 엔지니어에게 통용되는 정신은 아니라고 책에 나옵니다.

          저 역시도 같은 생각을 했으며, 이 책에서 나오는 소프트웨어 정신을 정답처럼 생각은 말되, 본받을 정신만 본받는 자세가 필요하다고 느꼈습니다.
      - layout: right
        title: 클린 코드
        caption: April 2022 - July 2022
        link: http://www.yes24.com/Product/Goods/11681152
        quote: >
          <mark>별점</mark> : ★★★★★
        description: |
          이 책은 클린하지 못한 코드를 점차 클린하게 만들어가는 과정을 보여주고 있습니다. 

          이 책 덕분에 제 코드가 보다 깔끔해졌습니다.

          사내 코드 리뷰 시에도 이 책의 내용을 레퍼런스 삼아 리뷰를 진행함으로써 제 의견의 신빙성을 더해줄 수 있었습니다.
      - layout: right
        title: 도메인 주도 설계 시작하기
        caption: May 2022 - June 2022
        link: https://kkoon9.tistory.com/366
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: |
          이 책을 통해 DDD를 도입하기 위한 전반적인 도메인과 애그리거트, 바운디드 컨텍스트 등을 익힐 수 있었습니다.

          더 나아가 이벤트 스토밍을 팀 내 도입하는 데 큰 도움을 받았습니다.

          이벤트 스토밍 관련 포스팅은 옆 링크를 확인해주세요!
      - layout: right
        title: Java 언어로 배우는 디자인 패턴 입문
        caption: March 2022 - April 2022
        link: http://www.yes24.com/Product/Goods/115576266
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: |
          이 책을 통해 디자인 패턴에 대한 내용을 이해할 수 있었습니다.

          예제 코드와 사고를 넓히기 위한 힌트를 제시해줌으로써 혼자서 생각해볼 수 있는 기회로 마련해줍니다.

          이 책에서 학습한 전략 패턴을 실무에 도입해본 경험이 있습니다.
      - layout: right
        title: 손에 잡히는 10분 정규 표현식
        caption: January 2022 - January 2022
        link: https://kkoon9.tistory.com/104
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: |
          이 책을 통해 정규표현식에 대한 내용을 이해할 수 있었습니다.

          정규표현식은 코딩테스트 뿐만 아니라, 실무에서도 자주 사용됩니다.

          저는 핸드폰 번호의 유효성 체크를 할 때에도 정규표현식을 사용했습니다.

          핸드폰 번호 외에도 여러 곳에서 사용될 수 있으니, 한 번쯤 읽어보시는 걸 추천드립니다.
      - layout: right
        title: 객체지향의 사실과 오해
        caption: September 2021 - November 2021
        link: https://www.youtube.com/watch?v=dJ5C4qRqAgA
        quote: >
          <mark>별점</mark> : ★★★☆☆
        description: |
          이 책을 통해 역할과 책임, 협력에 대한 내용을 이해할 수 있었습니다.

          읽어보면 아시겠지만, 반복되는 어구가 많습니다.

          중요하니까 반복한다고 느낄수도 있지만 조금은 지루하다고 느낄수도 있습니다.

          우아한객체지향에서 소개한 유튜브 영상도 있으니, 옆 링크 영상을 보고 구매하시는 걸 추천합니다.
      - layout: right
        title: effective java
        caption: August 2021 - October 2021
        link: http://www.yes24.com/Product/Goods/65551284
        quote: >
          <mark>별점</mark> : ★★★★★
        description: |
          이 책을 통해 Java에 대한 실력이 많이 늘었습니다.

          Java의 교과서라고 해도 될만큼 좋은 정보를 많이 담고 있습니다.

          중요하니까 여러 번 읽어보시는걸 추천드립니다.

          집 혹은 회사에 두시고, 개발하면서 찾아보는 것도 추천드립니다.
      - layout: right
        title: AWS 인프라 구축 가이드
        caption: December 2020 - February 2021
        link: http://www.yes24.com/Product/Goods/68799454
        quote: >
          <mark>별점</mark> : ★★☆☆☆
        description: |
          이 책을 통해 AWS EC2와 로드밸런서 구조를 알게 되었습니다.

          AWS 관련한 기초 지식을 얻기엔 최고의 책이었습니다.

          하지만 별점을 2점밖에 주지 않은 이유는 19년도에 나온 책이기 때문입니다.

          AWS 기술은 계속해서 발전하고 있기 때문에 만약 AWS 관련 책을 사시려면 가장 최근 책을 사시는 걸 추천드리는 마음에 2점을 주었습니다.

  - title: A Little More About Me
    layout: text
    content: |
      읽어주셔서 감사합니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]

# Analytics
analytics:
  provider:
    "google-gtag"
    # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-5GQ9HKMQRM"
    anonymize_ip: # true, false (default)
