# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 남궁권
title: Library Of Eric
email: rndrnjs2003@gmail.com
website: https://kkoon9.tistory.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: kkoon9
linkedin_username: nam-koong-kwon-7a320317a

# Additional icon links
# additional_links:
#   - title: Link name
#     icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#     url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About Me (Use this to override about section title)
about_profile_image: kkoon9.jpeg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 제가 읽었던 책을 소개하는 페이지입니다.

  저는 3년차 백엔드 개발자입니다.

  개발 서적을 주로 읽었기 때문에 백엔드 개발에 관심이 있으신 분들께 도움이 됐으면 좋겠습니다.

content:
  - title: Books
    layout: list
    content:
      - layout: right
        title: 도메인 주도 설계 시작하기
        caption: eg. May 2022 - June 2022
        link: http://www.yes24.com/Product/Goods/108431347
        quote: >
          <mark>별점</mark> : ★★★★☆
        description: | # this will include new lines to allow paragraphs
          이 책을 통해 DDD를 도입하기 위한 전반적인 도메인과 애그리거트, 바운디드 컨텍스트 등을 익힐 수 있었습니다.

          더 나아가 이벤트 스토밍을 팀 내 도입하는 데 큰 도움을 받았습니다.
      - layout: right
        title: 객체지향의 사실과 오해
        caption: eg. September 2021 - November 2021
        link: http://www.yes24.com/Product/Goods/18249021
        quote: >
          <mark>별점</mark> : ★★★☆☆
        description: | # this will include new lines to allow paragraphs
          이 책을 통해 역할과 책임, 협력에 대한 내용을 이해할 수 있었습니다.

          읽어보면 아시겠지만, 반복되는 어구가 많습니다.

          중요하니까 반복한다고 느낄수도 있지만 조금은 지루하다고 느낄수도 있습니다.

          우아한객체지향에서 소개한 유튜브 영상도 있으니, 이 영상을 보고 구매하셔도 좋다고 생각합니다.

          https://www.youtube.com/watch?v=dJ5C4qRqAgA
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      읽어주셔서 감사합니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
